- name: Install package
  ansible.builtin.apt:
    name: cron
    state: present
    update_cache: true

- name: Set PATH variable for root user crontab
  ansible.builtin.cron:
    name: PATH
    user: root
    env: true
    job: /usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
    state: present

- name: Set SHELL variable for root user crontab
  ansible.builtin.cron:
    name: SHELL
    user: root
    env: true
    job: /bin/bash
    state: present
